kind: Service
apiVersion: v1
metadata:
  name: grafana 
spec:
  
  type: LoadBalancer
  
  selector:
    app.kubernetes.io/instance: xap
    app.kubernetes.io/name: grafana  
  ports:
    
    - port: 3000
      targetPort: 3000
      name: grafana
