kind: Service
apiVersion: v1
metadata:
  name: grafana-lb
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: Owner=CSM, Project=CSM-LAB, Name=EKS-CSM-grafana-lb
spec:
  
  type: LoadBalancer
  
  selector:
    app.kubernetes.io/instance: xap
    app.kubernetes.io/name: grafana  
  ports:
    
    - port: 3000
      targetPort: 3000
      name: grafana
